### ISSUE TITLE
Investigate on how to integrate OBP library in the project

### ISSUE THREAD

**Issue by ankitjena** [coderwassananmol/BUB2#123]
Currently we are supporting Google Books and Panjab Digital Library. We are planning to integrate Open Book Publishers library too.

## TODO
- [x] See how we are downloading books from the other two libraries.
- [x] Check how to download book from Open Book Publishers
- [ ] Implement logic to download the book from OBP.

For any queries regarding this, contact in the slack channel.

**Comment by amandhamija98** [comment]
Hi, I am a gssoc participant, may I please be assigned this

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign this to me as part of GSSoC'20. I can make PR early.

**Comment by akshaysingh5** [comment]
I want to work on this issue. Please assign this to me.

**Comment by coderwassananmol** [comment]
This is done. We need to add the service to integrate it.
